import = ["/Users/ssettipalli/.config/dracula.toml"]

#[colors.bright]
#black = "#3B4252"
#blue = "#569CD6"
#cyan = "#29B8DB"
#green = "#23D18B"
#magenta = "#C586C0"
#red = "#D54646"
#white = "#ECEFF4"
#yellow = "#D7BA7D"

#[colors.normal]
#black = "#3B4252"
#blue = "#569CD6"
#cyan = "#29B8DB"
#green = "#23D18B"
#magenta = "#C586C0"
#red = "#D54646"
#white = "#abb2bf"
#yellow = "#D7BA7D"

#[colors.primary]
#background = "#1E1E1E"
#foreground = "#D8DEE9"

[cursor.style]
blinking = "On"
shape = "Block"

[font]
size = 18.0

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "NumpadAdd"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "NumpadSubtract"
mods = "Command"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Command"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000

[window]
dynamic_title = true
title = "Alacritty"

[window.dimensions]
columns = 160
lines = 50

[window.padding]
x = 2
y = 2
